name: Trigger Supabase Function Daily

on:
  schedule:
    - cron: '*/1 * * * *' # Run every minute for testing

jobs:
  trigger-function:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make HTTP Request to Supabase Edge Function
        run: |
          # The entire 'curl' command should be on a single logical line.
          # The backslashes '\' are for line continuation in bash.
          curl -X GET \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZXF1eHB4Zm9ld2VqamNzYWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTczOTIsImV4cCI6MjA2MTQ5MzM5Mn0.5bMubfBJMBho7dS7Z_4BFwyOVW_45pOXukannFqZwTU" \
          -H "Content-Type: application/json" \
          "https://esequxpxfoewejjcsagm.supabase.co/functions/v1/check-subscription-status"
